import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import Image from "next/image";
import bilalWaved from "../public/paroo-n-bilal.jpg";
import designed from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Bilal Shafqat Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between ">
            <h1 className="text-xl font-burtons dark:text-slate-200">
              Developed By Bilal
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className="cursor-pointer text-2xl dark:text-slate-200"
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r  from-cyan-500 to-teal-500  text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10">
            <div className="relative mx-auto shadow-lg bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
              <Image
                src={bilalWaved}
                layout="fill"
                objectFit="cover"
                alt="waving"
              />
            </div>
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl">
              Bilal Shafqat
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-slate-200">
              Developer And Designer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-slate-200">
              Freelancer providing services for programming and design content
              needs. Join me down below and let's get cracking!
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-teal-600">
              <a href="#">
                <AiFillTwitterCircle />
              </a>
              <a href="#">
                <AiFillLinkedin />
              </a>
              <a href="#">
                <AiFillYoutube />
              </a>
            </div>
          </div>
        </section>
        <hr className="mb-6" />
        <section>
          <div className="text-center md:text-xl max-w-xl mx-auto">
            <h3 className="text-2xl py-2 font-semibold	 md:text-3xl dark:text-slate-200">
              Services I Offer
            </h3>
            <p className="text-md py-2 leading-8 text-gray-80 dark:text-slate-200">
              Since the beginning of my journey as a freelance developer and
              designer, I've done remote work for
              <span className="text-teal-500"> agencies</span> consulted for
              <span className="text-teal-500"> startup</span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-80 dark:text-slate-200">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="lg:flex gap-10 max-w-screen-lg	mx-auto">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={designed}
                width={100}
                height={100}
                alt="designs"
                className="mx-auto"
              />
              <h3 className="text-lg font-semibold pt-8 pb-2">Web Designing</h3>
              <p className="py-2">
                Creating elegant, minimalistic designs for your need.
              </p>
              <h4 className="py-4 font-semibold	 text-teal-600">
                DESIGNING TOOLS
              </h4>
              <p className="text=gray-800 py-1">Adobe Photoshop</p>
              <p className="text=gray-800 py-1">Adobe Illustraor</p>
              <p className="text=gray-800 py-1">Corel Draw</p>
              <p className="text=gray-800 py-1">Canva</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={consulting}
                width={100}
                height={100}
                alt="designs"
                className="mx-auto"
              />
              <h3 className="text-lg font-semibold pt-8 pb-2">Consulting </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs design theory.
              </p>
              <h4 className="py-4 font-semibold	 text-teal-600">
                CONSULTING SERVICES
              </h4>
              <p className="text=gray-800 py-1">Designing</p>
              <p className="text=gray-800 py-1">Development</p>
              <p className="text=gray-800 py-1">Digital Marketing</p>
              <p className="text=gray-800 py-1">Ecommerce</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white">
              <Image
                src={code}
                width={100}
                height={100}
                alt="designs"
                className="mx-auto"
              />
              <h3 className="text-lg font-semibold	 pt-8 pb-2">Programming</h3>
              <p className="py-2">
                Creating elegant designs suited for your needs design theory.
              </p>
              <h4 className="py-4 font-semibold	 text-teal-600">
                PROGRAMING SERVICES
              </h4>
              <p className="text=gray-800 py-1">Web Development</p>
              <p className="text=gray-800 py-1">Mobile Development</p>
              <p className="text=gray-800 py-1">E-Commerce Development</p>
              <p className="text=gray-800 py-1">Fintech</p>
            </div>
          </div>
        </section>
        <hr className="mb-6" />
        <section>
          <div className="text-center md:text-xl max-w-xl mx-auto">
            <h3 className="text-2xl py-2 font-semibold md:text-3xl dark:text-slate-200">
              Portfolio
            </h3>
            <p className="text-md py-2 leading-8 text-gray-80 dark:text-slate-200">
              Since the beginning of my journey as a freelance developer and
              designer, I've done remote work for
              <span className="text-teal-500"> agencies</span> consulted for
              <span className="text-teal-500"> startup</span> and collaborated
              with talented people to create digital products for both business
              and consumer use.
            </p>
            <p className="text-md py-2 leading-8 text-gray-80 dark:text-slate-200">
              I offer from a wide range of services, including programming and
              teaching.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap  max-w-screen-lg mx-auto">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                alt="web"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                alt="web"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                alt="web"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                alt="web"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                alt="web"
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                alt="web"
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
